/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'

const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/blog/$postId': typeof BlogPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/blog/$postId': typeof BlogPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/blog/$postId': typeof BlogPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biografia' | '/blog/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biografia' | '/blog/$postId'
  id: '__root__' | '/' | '/biografia' | '/blog/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiografiaRoute: typeof BiografiaRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiografiaRoute: BiografiaRoute,
  BlogPostIdRoute: BlogPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
